/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace TreatmentLogger {
      
    export type TreatmentStruct = {id: BigNumberish, patientId: string, service: string, cost: BigNumberish, timestamp: BigNumberish}

    export type TreatmentStructOutput = [id: bigint, patientId: string, service: string, cost: bigint, timestamp: bigint] & {id: bigint, patientId: string, service: string, cost: bigint, timestamp: bigint }
  
    }

  export interface TreatmentLoggerInterface extends Interface {
    getFunction(nameOrSignature: "addTreatment" | "getAllTreatments" | "getTreatment" | "treatmentCount" | "treatments"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TreatmentAdded"): EventFragment;

    encodeFunctionData(functionFragment: 'addTreatment', values: [string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllTreatments', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTreatment', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'treatmentCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'treatments', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addTreatment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllTreatments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTreatment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treatmentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treatments', data: BytesLike): Result;
  }

  
    export namespace TreatmentAddedEvent {
      export type InputTuple = [id: BigNumberish, patientId: string, service: string, cost: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [id: bigint, patientId: string, service: string, cost: bigint, timestamp: bigint];
      export interface OutputObject {id: bigint, patientId: string, service: string, cost: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TreatmentLogger extends BaseContract {
    
    connect(runner?: ContractRunner | null): TreatmentLogger;
    waitForDeployment(): Promise<this>;

    interface: TreatmentLoggerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addTreatment: TypedContractMethod<
      [_patientId: string, _service: string, _cost: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAllTreatments: TypedContractMethod<
      [],
      [TreatmentLogger.TreatmentStructOutput[]],
      'view'
    >
    

    
    getTreatment: TypedContractMethod<
      [_id: BigNumberish, ],
      [TreatmentLogger.TreatmentStructOutput],
      'view'
    >
    

    
    treatmentCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    treatments: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint] & {id: bigint, patientId: string, service: string, cost: bigint, timestamp: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addTreatment'): TypedContractMethod<
      [_patientId: string, _service: string, _cost: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllTreatments'): TypedContractMethod<
      [],
      [TreatmentLogger.TreatmentStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTreatment'): TypedContractMethod<
      [_id: BigNumberish, ],
      [TreatmentLogger.TreatmentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'treatmentCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'treatments'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint] & {id: bigint, patientId: string, service: string, cost: bigint, timestamp: bigint }],
      'view'
    >;

    getEvent(key: 'TreatmentAdded'): TypedContractEvent<TreatmentAddedEvent.InputTuple, TreatmentAddedEvent.OutputTuple, TreatmentAddedEvent.OutputObject>;

    filters: {
      
      'TreatmentAdded(uint256,string,string,uint256,uint256)': TypedContractEvent<TreatmentAddedEvent.InputTuple, TreatmentAddedEvent.OutputTuple, TreatmentAddedEvent.OutputObject>;
      TreatmentAdded: TypedContractEvent<TreatmentAddedEvent.InputTuple, TreatmentAddedEvent.OutputTuple, TreatmentAddedEvent.OutputObject>;
    
    };
  }